### PR TITLE
WIP: Show loading indicator when waiting for data to load

### PR DESCRIPTION
**Pull request by haraldreingruber**
We (@dbartholomae, @3ng7n33r, @dpolivaev and myself) started working on #161 during our Hacktoberfest Mob-Programming session, but were not able to finish up the improvement during the session.

I will try to continue working on that PR during next week.

@mrozbarry if you find some time it would be great if you have a quick look over the changes. Let me know if there is anything going in a unexpected direction because of us not knowing the big picture that well.

### CODE REVIEW

**Comment by mrozbarry** [comment]
@haraldreingruber is there any other work that needs to be done on this?

**Comment by haraldreingruber** [comment]
@mrozbarry We added the initialLoadingComplete flag to the state object and created some first tests. The actual UI part is still missing...

As I started a new job recently, I am afraid I won't be able to continue on that any time soon.

**Comment by mrozbarry** [comment]
@haraldreingruber okay, I'm working on some UI design for mobtime, so maybe we can think through what a progress bar/spinner should look like while we're at it.

And no worries, congratulations on the new job!

**Comment by mrozbarry** [comment]
I'm going to close this for now, but if it gets into a working state, feel free to re-open

**Pull request closed without merging**
